### ISSUE TITLE
UsageError: Line magic function `%install_ext` not found.

### ISSUE THREAD

**Issue by pachocamacho1990** [azjps/ipython-geogebra#1]
Hi!!

I wanted to use your geogebratube_iframe to create some interactive jupyter notebooks with Geogebra  for my class at the university, however I get this error: 

UsageError: Line magic function `%install_ext` not found.

does it have something to do with: https://github.com/ipython/ipython/issues/8634. I am not sure how to fix this with the most recent version of python.

**Comment by azjps** [comment]
Sorry for the delayed reply, yes it seems that `%install_ext` was deprecated/removed. 
I've updated the notebook to `import` the extension directly https://github.com/azjps/ipython-geogebra/blob/master/examples/geogebratube_iframe.ipynb, let me know if that doesn't work still.
